In [49]:
from IPython.display import display
import numpy as np
print(np.__version__)
np.show_config()

1.11.2
blas_opt_info:
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    library_dirs = ['/Users/joshreuben/anaconda/envs/gcloud/lib']
    include_dirs = ['/Users/joshreuben/anaconda/envs/gcloud/include']
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
openblas_lapack_info:
  NOT AVAILABLE
blas_mkl_info:
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    library_dirs = ['/Users/joshreuben/anaconda/envs/gcloud/lib']
    include_dirs = ['/Users/joshreuben/anaconda/envs/gcloud/include']
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
lapack_mkl_info:
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    library_dirs = ['/Users/joshreuben/anaconda/envs/gcloud/lib']
    include_dirs = ['/Users/joshreuben/anaconda/envs/gcloud/include']
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
lapack_opt_info:
    define_macros = [('S

In [3]:
# Find indices of non-zero elements
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

In [4]:
# Create a null vector of size 10 but the fifth value which is 1
Z = np.zeros(10)
Z[4] = 1
Z

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

In [5]:
# Reverse a vector
Z = np.arange(50)
Z = Z[::-1]
Z

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [6]:
# Create a 3x3 matrix with values ranging from 0 to 8
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
# Create a 3x3 identity matrix
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [8]:
# Create a 3x3x3 array with random values
Z = np.random.random((3,3,3))
Z

array([[[ 0.28301764,  0.8821066 ,  0.46903496],
        [ 0.88179285,  0.46129278,  0.44852511],
        [ 0.965885  ,  0.34011549,  0.8504536 ]],

       [[ 0.53292566,  0.46149705,  0.9777551 ],
        [ 0.54748536,  0.10597668,  0.74989096],
        [ 0.83274851,  0.54473448,  0.59626862]],

       [[ 0.35499555,  0.52679024,  0.11454035],
        [ 0.65961085,  0.17244782,  0.22685877],
        [ 0.20752784,  0.68383831,  0.46745751]]])

In [ ]:
Zmin, Zmax = Z.min(), Z.max()

In [9]:
# Create a 2d array with 1 on the border and 0 inside
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
Z

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [10]:
0 * np.nan

nan

In [11]:
# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [12]:
np.diag(np.arange(4))

array([[0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3]])

In [13]:
# 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element
np.unravel_index(100,(6,7,8))

(1, 5, 4)

In [14]:
# 19. Create a checkerboard 8x8 matrix using the tile function
np.tile( np.array([[0,1],[1,0]]), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [15]:
# 20. Normalize a 5x5 random matrix ??
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
Z

array([[ 0.72130736,  0.13723328,  0.6195119 ,  0.01622095,  0.53980101],
       [ 0.        ,  0.57219114,  0.55340231,  0.14897345,  0.68257836],
       [ 0.05100839,  0.26792655,  0.12512258,  0.47930118,  0.50110633],
       [ 0.9827469 ,  0.16452689,  0.89626389,  0.52729393,  0.50534343],
       [ 0.221462  ,  0.50499674,  1.        ,  0.50456872,  0.44175266]])

In [17]:
# 22. Multiply a 5x3 matrix by a 3x2 matrix
np.dot(np.ones((5,3)), np.ones((3,2)))

array([[ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.]])

In [18]:
# 23. Given a 1D array, negate all elements which are between 3 and 8, in place
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
Z

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

In [24]:
np.random.uniform(-10,+10,10)

array([ 6.14176359, -2.7928077 ,  1.13319646, -6.05758934, -1.61706102,
        1.05706486, -0.17232785, -3.19365079,  2.76283241, -4.628869  ])

In [25]:
# Create a vector of size 10 with values ranging from 0 to 1, both excluded
np.linspace(0,1,12,endpoint=True)[1:-1]

array([ 0.09090909,  0.18181818,  0.27272727,  0.36363636,  0.45454545,
        0.54545455,  0.63636364,  0.72727273,  0.81818182,  0.90909091])

In [30]:
# 32. Create a random vector of size 10 and sort it
Z = np.random.random(10)
Z.sort()
Z

array([ 0.0911789 ,  0.34080747,  0.40616981,  0.40864783,  0.50465644,
        0.57428132,  0.60443836,  0.60616351,  0.78381211,  0.81527755])

In [33]:
# sum a small array faster than np.sum
Z = np.arange(10)
np.add.reduce(Z)

45

In [34]:
np.sum(Z)

45

In [35]:
# 34. Consider two random array A anb B, check if they are equal
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
np.allclose(A,B)

False

In [36]:
# 36. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[ 1.1619684   0.85284682  0.72840285  0.80777078  0.48246597  0.62732369
  0.73808616  0.9821536   0.97020368  0.83158235]
[ 1.0047622   1.18145044  1.40600747  0.74767148  0.7002249   0.60645203
  0.33382856  0.06796689  0.66350911  0.09626606]


In [39]:
# 73. Compute a matrix rank
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
rank

10

In [41]:
# find the most frequent value in an array
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

2


# Arrays

In [51]:
a = np.array([1, 2, 3])  # Create a rank 1 array
display(type(a))            
display( a.shape )           
display( a)  
a[0] = 5                 # Change an element of the array
display( a )                 

b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
display( b.shape )                    
display( b )  

numpy.ndarray

(3,)

array([1, 2, 3])

array([5, 2, 3])

(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
a = np.zeros((2,2))
b = np.ones((1,2))
c = np.full((2,2), 7)
d = np.eye(2)
e = np.random.random((2,2))
display(a,b,c,d,e)

/Users/joshreuben/anaconda/envs/gcloud/lib/python3.5/site-packages/numpy/core/numeric.py:301: FutureWarning: in the future, full((2, 2), 7) will return an array of dtype('int64')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


array([[ 0.,  0.],
       [ 0.,  0.]])

array([[ 1.,  1.]])

array([[ 7.,  7.],
       [ 7.,  7.]])

array([[ 1.,  0.],
       [ 0.,  1.]])

array([[ 0.18006831,  0.63362012],
       [ 0.84503578,  0.47258199]])

In [53]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
display(a[:2, 1:3])
display(a[1,1])

array([[2, 3],
       [6, 7]])

6

In [54]:
display (a[1, :])    # Rank 1 view of the second row of a  
display (a[1:2, :])  # Rank 2 view of the second row of a
display (a[:, 1])
display (a[:, 1:2])

array([5, 6, 7, 8])

array([[5, 6, 7, 8]])

array([ 2,  6, 10])

array([[ 2],
       [ 6],
       [10]])

In [55]:
display(a[[0, 0], [1, 1]])
display(np.array([a[0, 1], a[0, 1]]))

array([2, 2])

array([2, 2])

In [57]:
a = np.array([[1,2], [3, 4], [5, 6]])
bool_idx = ( a > 2)
display(bool_idx)
display(a[bool_idx])

array([[False, False],
       [ True,  True],
       [ True,  True]], dtype=bool)

array([3, 4, 5, 6])

In [61]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
display (x + y)
display (x.dot(y))
display(x.T)
display(np.sum(x))
display(np.sum(x, axis=0)) # sum of each col
display(np.sum(x, axis=1)) # sum of each row

array([[  6.,   8.],
       [ 10.,  12.]])

array([[ 19.,  22.],
       [ 43.,  50.]])

array([[ 1.,  3.],
       [ 2.,  4.]])

10.0

array([ 4.,  6.])

array([ 3.,  7.])

# broadcasting
work with arrays of different shapes

In [62]:
# add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
display( y)

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])