In [1]:
from IPython.display import display
import numpy as np
print(np.__version__)
np.show_config()

1.11.2
lapack_mkl_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/joshreuben/anaconda/envs/gcloud/include']
    library_dirs = ['/Users/joshreuben/anaconda/envs/gcloud/lib']
lapack_opt_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/joshreuben/anaconda/envs/gcloud/include']
    library_dirs = ['/Users/joshreuben/anaconda/envs/gcloud/lib']
blas_mkl_info:
    libraries = ['mkl_intel_lp64', 'mkl_intel_thread', 'mkl_core', 'iomp5', 'pthread']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/joshreuben/anaconda/envs/gcloud/include']
    library_dirs = ['/Users/joshreuben/anaconda/envs/gcloud/lib']
openblas_lapack_info:
  NOT AVAILABLE
blas_opt_info:
    libraries = ['mkl_in

In [8]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <http://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <http://ipython.scipy.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particu

In [3]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_globals',
 '_import_tools',
 '_mat',
 'ab

# 100 numpy exercises

In [22]:
def print_members(obj):
    for key in dir(obj):
        value = getattr(obj, key)
        doc = (value.__doc__ or '').split('.', 1)[0]
        print('\n%s: %s' % (key, doc))

print_members(np)


ALLOW_THREADS: int(x=0) -> integer
int(x, base=10) -> integer

Convert a number or string to an integer, or return 0 if no arguments
are given

BUFSIZE: int(x=0) -> integer
int(x, base=10) -> integer

Convert a number or string to an integer, or return 0 if no arguments
are given

CLIP: int(x=0) -> integer
int(x, base=10) -> integer

Convert a number or string to an integer, or return 0 if no arguments
are given

    The warning raised when casting a complex dtype to a real dtype

DataSource: 
    DataSource(destpath='

ERR_CALL: int(x=0) -> integer
int(x, base=10) -> integer

Convert a number or string to an integer, or return 0 if no arguments
are given

ERR_DEFAULT: int(x=0) -> integer
int(x, base=10) -> integer

Convert a number or string to an integer, or return 0 if no arguments
are given

ERR_IGNORE: int(x=0) -> integer
int(x, base=10) -> integer

Convert a number or string to an integer, or return 0 if no arguments
are given

ERR_LOG: int(x=0) -> integer
int(x, base=10) -> int

In [3]:
# Find indices of non-zero elements
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

In [4]:
# Create a null vector of size 10 but the fifth value which is 1
Z = np.zeros(10)
Z[4] = 1
Z

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

In [5]:
# Reverse a vector
Z = np.arange(50)
Z = Z[::-1]
Z

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [6]:
# Create a 3x3 matrix with values ranging from 0 to 8
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
# Create a 3x3 identity matrix
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [8]:
# Create a 3x3x3 array with random values
Z = np.random.random((3,3,3))
Z

array([[[ 0.28301764,  0.8821066 ,  0.46903496],
        [ 0.88179285,  0.46129278,  0.44852511],
        [ 0.965885  ,  0.34011549,  0.8504536 ]],

       [[ 0.53292566,  0.46149705,  0.9777551 ],
        [ 0.54748536,  0.10597668,  0.74989096],
        [ 0.83274851,  0.54473448,  0.59626862]],

       [[ 0.35499555,  0.52679024,  0.11454035],
        [ 0.65961085,  0.17244782,  0.22685877],
        [ 0.20752784,  0.68383831,  0.46745751]]])

In [ ]:
Zmin, Zmax = Z.min(), Z.max()

In [9]:
# Create a 2d array with 1 on the border and 0 inside
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
Z

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [10]:
0 * np.nan

nan

In [11]:
# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [12]:
np.diag(np.arange(4))

array([[0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3]])

In [13]:
# 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element
np.unravel_index(100,(6,7,8))

(1, 5, 4)

In [14]:
# 19. Create a checkerboard 8x8 matrix using the tile function
np.tile( np.array([[0,1],[1,0]]), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [15]:
# 20. Normalize a 5x5 random matrix ??
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
Z

array([[ 0.72130736,  0.13723328,  0.6195119 ,  0.01622095,  0.53980101],
       [ 0.        ,  0.57219114,  0.55340231,  0.14897345,  0.68257836],
       [ 0.05100839,  0.26792655,  0.12512258,  0.47930118,  0.50110633],
       [ 0.9827469 ,  0.16452689,  0.89626389,  0.52729393,  0.50534343],
       [ 0.221462  ,  0.50499674,  1.        ,  0.50456872,  0.44175266]])

In [17]:
# 22. Multiply a 5x3 matrix by a 3x2 matrix
np.dot(np.ones((5,3)), np.ones((3,2)))

array([[ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.],
       [ 3.,  3.]])

In [18]:
# 23. Given a 1D array, negate all elements which are between 3 and 8, in place
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
Z

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

In [24]:
np.random.uniform(-10,+10,10)

array([ 6.14176359, -2.7928077 ,  1.13319646, -6.05758934, -1.61706102,
        1.05706486, -0.17232785, -3.19365079,  2.76283241, -4.628869  ])

In [25]:
# Create a vector of size 10 with values ranging from 0 to 1, both excluded
np.linspace(0,1,12,endpoint=True)[1:-1]

array([ 0.09090909,  0.18181818,  0.27272727,  0.36363636,  0.45454545,
        0.54545455,  0.63636364,  0.72727273,  0.81818182,  0.90909091])

In [30]:
# 32. Create a random vector of size 10 and sort it
Z = np.random.random(10)
Z.sort()
Z

array([ 0.0911789 ,  0.34080747,  0.40616981,  0.40864783,  0.50465644,
        0.57428132,  0.60443836,  0.60616351,  0.78381211,  0.81527755])

In [33]:
# sum a small array faster than np.sum
Z = np.arange(10)
np.add.reduce(Z)

45

In [34]:
np.sum(Z)

45

In [35]:
# 34. Consider two random array A anb B, check if they are equal
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
np.allclose(A,B)

False

In [36]:
# 36. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[ 1.1619684   0.85284682  0.72840285  0.80777078  0.48246597  0.62732369
  0.73808616  0.9821536   0.97020368  0.83158235]
[ 1.0047622   1.18145044  1.40600747  0.74767148  0.7002249   0.60645203
  0.33382856  0.06796689  0.66350911  0.09626606]


In [39]:
# 73. Compute a matrix rank
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
rank

10

In [41]:
# find the most frequent value in an array
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

2


# Python Numpy Tutorial

## Arrays

### array shapes

In [38]:
a = np.array([1, 2, 3])  # Create a rank 1 array
display(type(a))            
display( a.shape )           
display( a)  
a[0] = 5                 # Change an element of the array
display( a )                 

b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
display(np.ndim(b))  # rank
display( b.shape )                    
display( b )  

numpy.ndarray

(3,)

array([1, 2, 3])

array([5, 2, 3])

2

(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

### array creation

In [52]:
a = np.zeros((2,2))
b = np.ones((1,2))
c = np.full((2,2), 7)
d = np.eye(2)
e = np.random.random((2,2))
display(a,b,c,d,e)

/Users/joshreuben/anaconda/envs/gcloud/lib/python3.5/site-packages/numpy/core/numeric.py:301: FutureWarning: in the future, full((2, 2), 7) will return an array of dtype('int64')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


array([[ 0.,  0.],
       [ 0.,  0.]])

array([[ 1.,  1.]])

array([[ 7.,  7.],
       [ 7.,  7.]])

array([[ 1.,  0.],
       [ 0.,  1.]])

array([[ 0.18006831,  0.63362012],
       [ 0.84503578,  0.47258199]])

## Array indexing

### slicing:

In [25]:

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
display(a[:2, 1:3])  #rows up to 2, columns from 1 to 2
display(a[1,1])

array([[2, 3],
       [6, 7]])

6

In [26]:
display (a[1, :])    # Rank 1 view of the second row of a  
display (a[1:2, :])  # Rank 2 view of the second row of a
display (a[:, 1])
display (a[:, 1:2])

array([5, 6, 7, 8])

array([[5, 6, 7, 8]])

array([ 2,  6, 10])

array([[ 2],
       [ 6],
       [10]])

### indexing

In [27]:
display(a[[0, 0], [1, 1]])
display(np.array([a[0, 1], a[0, 1]]))

array([2, 2])

array([2, 2])

### Boolean array indexing



In [29]:
a = np.array([[1,2], [3, 4], [5, 6]])
bool_idx = ( a > 2)
display(bool_idx)
display(a[bool_idx])

array([[False, False],
       [ True,  True],
       [ True,  True]], dtype=bool)

array([3, 4, 5, 6])

## datatypes

In [47]:
x = np.array([1, 2])  # Let numpy choose the datatype
display (x.dtype)         

x = np.array([1.0, 2.0])  
display (x.dtype)             

x = np.array([1, 2], dtype=np.int64)  # Force a particular datatype
print (x.dtype)                         

dtype('int64')

dtype('float64')

dtype('int64')

## Array math 

### element-wise

In [52]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print (x + y)
print (x.dot(y))
print(x.T)
print(np.sum(x))
print(np.sum(x, axis=0)) # sum of each col
print(np.sum(x, axis=1)) # sum of each row

[[  6.   8.]
 [ 10.  12.]]
[[ 19.  22.]
 [ 43.  50.]]
[[ 1.  3.]
 [ 2.  4.]]
10.0
[ 4.  6.]
[ 3.  7.]


### linear algebra

In [56]:
v = np.array([9,10])
w = np.array([11, 12])

display(x)
display(x.T) #transpose
# Inner product of vectors
display (np.dot(v, w))

# Matrix / vector product
display (np.dot(x, v))

# Matrix / matrix product
display (np.dot(x, y))

display (np.sum(x))  # Compute sum of all elements
display (np.sum(x, axis=0))  # Compute sum of each column
display (np.sum(x, axis=1))  # Compute sum of each row



array([[ 1.,  2.],
       [ 3.,  4.]])

array([[ 1.,  3.],
       [ 2.,  4.]])

219

array([ 29.,  67.])

array([[ 19.,  22.],
       [ 43.,  50.]])

10.0

array([ 4.,  6.])

array([ 3.,  7.])

## broadcasting
work with arrays of different shapes

In [57]:
# add the vector v to each row of the matrix x, storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
display(x)
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
display( y)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [76]:
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
z = np.reshape(v, (3, 1))
display( z.shape ) 
display (z)
display (v * z)

x = np.array([[1,2,3], [4,5,6]]) # x has shape (2, 3)
display (x)
display (x + v) # Add a vector to each row of a matrix x, broadcast v (3,) to (2, 3)

print ((x.T + w).T) # Add a vector to each column of a matrix - transpose x from (2, 3) to (3, 2) broadcast w from (2,)



(3, 1)

array([[1],
       [2],
       [3]])

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

array([[1, 2, 3],
       [4, 5, 6]])

array([[2, 4, 6],
       [5, 7, 9]])

[[ 5  6  7]
 [ 9 10 11]]
